trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
variables:
  - group: wittyvars

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g wittycli
  displayName: 'npm install'

- script: |
    export NEW_WIT_AUTH_TOKEN=$(wittycli import --file ./model/model.zip --name "witcli$(BUILD.BUILDID)" --private --dot access_token --wait)
    echo $NEW_WIT_AUTH_TOKEN
    echo "##vso[task.setvariable variable=NEW_WIT_AUTH_TOKEN;isOutput=true]$NEW_WIT_AUTH_TOKEN"
  displayName: 'import model'
  name: 'importzip'
      
- script: |
    wittycli test --auth $(importzip.NEW_WIT_AUTH_TOKEN) --file ./test/wit_test.json --parallel 5
  displayName: 'test model'